### ISSUE TITLE
Where is it for maven?

### ISSUE THREAD

**Issue by jottinger** [tomaytotomato/location4j#5]
**Question**
I added location4j to a project to try it out in a maven pom.xml. Maven is unable to locate it; looked on mvnrepository.com and it's not there, either. Where is the artifact?

**Sample code**

**Comment by tomaytotomato** [comment]
Thanks,

I just checked and I forgot to publish it.

Hopefully it will be available soon (I just clicked publish)

![image](https://github.com/user-attachments/assets/6436acaa-a663-4c4b-9c23-928be2e0b851)

**Comment by tomaytotomato** [comment]
Should be available now @jottinger 

https://central.sonatype.com/artifact/com.tomaytotomato/location4j 

Good spot! :sunglasses:
