### ISSUE TITLE
[IMPROVEMENT] use .bin for location4j data instead of the json

### ISSUE THREAD

**Issue by jottinger** [tomaytotomato/location4j#9]
**Summary** 
The source tree has a binary-encoded version of the data (created via java serialization, which may or may not be the best choice, but that's a separate concern). The artifact for 1.0.0 (the only one available) has the JSON file in text form. 

1. The artifact should have the .bin instead, OR the JSON should be compressed in the artifact.
2. If fix number 1 is applied (with the .bin, not compression), the resource file should be loaded canonically (i.e., *always* from the jar and not from "any file with the right name in the classpath" - otherwise Java serialization issues MAY rear their ugly heads.

**Comment by tomaytotomato** [comment]
I just merged this here - https://github.com/tomaytotomato/location4j/pull/6

I am going to do another release soon with the `location4j.bin` and no more JSON or Jackson dependency

There was some improvements from this listed in the PR.

I will create an issue for point #2
